version: '3.8'

services:
  odoo:
    image: odoo:16
    container_name: odoo-team2
    depends_on:
      - db
    ports:
      - 8088:8069
    networks:
      - odoo-network
    environment:
      - COMPOSE_CONVERT_WINDOWS_PATHS=1 # for windows
    volumes:
      - odoo-data:/var/lib/odoo
      - ./odoo.conf:/etc/odoo/odoo.conf
      - ./additional-addons:/mnt/additional-addons
      - ./addons:/mnt/addons
    logging:
      options:
        max-size: 10m
    command: --dev=qweb,xml
    stdin_open: true
    tty: true

  db:
    image: postgres:15
    container_name: db
    ports:
      - 5488:5432
    networks:
      - odoo-network
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
    volumes:
      - db-data:/var/lib/postgresql/data
    logging:
      options:
        max-size: 10m

volumes:
  odoo-data:
  odoo-addons:
  db-data:
networks:
  odoo-network:
